"""
End-to-end test suite for the multi-agent financial risk analysis pipeline.

Run with::

    pytest tests/ -v

All tests use a synthetic 3-page PDF generated by reportlab with
realistic-but-fictional numbers designed to trigger specific risk
conditions:
    - debt_to_equity ≈ 2.8  (CRITICAL)
    - current_ratio  ≈ 0.9  (CRITICAL)
    - declining net income over 3 quarters
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import List

import pytest

# ── Ensure project root is importable ───────────────────────────────
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))


# ═════════════════════════════════════════════════════════════════════
# SYNTHETIC PDF FIXTURE
# ═════════════════════════════════════════════════════════════════════


@pytest.fixture
def synthetic_pdf(tmp_path) -> Path:
    """Generate a 3-page synthetic financial PDF using reportlab.

    Numbers are chosen to produce:
    - debt_to_equity ≈ 2.8   (total_debt=1,400M / total_equity=500M)
    - current_ratio  ≈ 0.9   (current_assets=450M / current_liabilities=500M)
    - declining net income:   Q1=120M → Q2=85M → Q3=42M

    Returns
    -------
    Path
        Path to the generated PDF file.
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate,
        Table,
        TableStyle,
        Paragraph,
        Spacer,
        PageBreak,
    )
    from reportlab.lib.styles import getSampleStyleSheet

    pdf_path = tmp_path / "acme_corp_annual_2024.pdf"
    doc = SimpleDocTemplate(str(pdf_path), pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # ── Shared table style ──────────────────────────────────────────
    table_style = TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("TOPPADDING", (0, 1), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ]
    )

    # ── PAGE 1: Balance Sheet ───────────────────────────────────────
    elements.append(Paragraph("ACME Corporation — Annual Report 2024", styles["Title"]))
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph("Consolidated Balance Sheet (USD millions)", styles["Heading2"]))
    elements.append(Spacer(1, 0.15 * inch))

    balance_data = [
        ["Item", "2024", "2023"],
        ["Total Assets", "2,100", "2,050"],
        ["Current Assets", "450", "520"],
        ["Cash and Cash Equivalents", "120", "180"],
        ["Short-term Investments", "80", "90"],
        ["Accounts Receivable", "150", "160"],
        ["Inventory", "100", "90"],
        ["Total Liabilities", "1,600", "1,500"],
        ["Current Liabilities", "500", "480"],
        ["Total Debt", "1,400", "1,300"],
        ["Total Equity", "500", "550"],
        ["Shareholder Equity", "500", "550"],
    ]

    tbl = Table(balance_data, colWidths=[2.5 * inch, 1.5 * inch, 1.5 * inch])
    tbl.setStyle(table_style)
    elements.append(tbl)
    elements.append(PageBreak())

    # ── PAGE 2: P&L Statement ───────────────────────────────────────
    elements.append(
        Paragraph("Income Statement — Quarterly Breakdown (USD millions)", styles["Heading2"])
    )
    elements.append(Spacer(1, 0.15 * inch))

    pnl_data = [
        ["Item", "Q1 2024", "Q2 2024", "Q3 2024"],
        ["Revenue", "800", "780", "750"],
        ["Cost of Goods Sold", "520", "530", "545"],
        ["Gross Income", "280", "250", "205"],
        ["Operating Expenses", "120", "125", "128"],
        ["Operating Income", "160", "125", "77"],
        ["Interest Expense", "25", "27", "30"],
        ["Net Income", "120", "85", "42"],
    ]

    tbl2 = Table(
        pnl_data,
        colWidths=[2.0 * inch, 1.3 * inch, 1.3 * inch, 1.3 * inch],
    )
    tbl2.setStyle(table_style)
    elements.append(tbl2)

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(
        Paragraph(
            "Note: Net income declined from 120M in Q1 to 42M in Q3 due to "
            "rising cost of goods sold and increased interest expense. "
            "Profit margin fell from 15.0% to 5.6%.",
            styles["Normal"],
        )
    )
    elements.append(PageBreak())

    # ── PAGE 3: Cash Flow Statement ─────────────────────────────────
    elements.append(
        Paragraph("Cash Flow Statement — Full Year (USD millions)", styles["Heading2"])
    )
    elements.append(Spacer(1, 0.15 * inch))

    cashflow_data = [
        ["Item", "2024", "2023"],
        ["Cash from Operations", "210", "290"],
        ["Capital Expenditures", "-95", "-80"],
        ["Free Cash Flow", "115", "210"],
        ["Dividends Paid", "-60", "-55"],
        ["Debt Repayment", "-50", "-70"],
        ["Net Change in Cash", "-60", "5"],
    ]

    tbl3 = Table(cashflow_data, colWidths=[2.5 * inch, 1.5 * inch, 1.5 * inch])
    tbl3.setStyle(table_style)
    elements.append(tbl3)

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(
        Paragraph(
            "Cash from operations declined 28% year-over-year. "
            "Free cash flow dropped 45% from 210M to 115M. "
            "The company drew down cash reserves by 60M to fund operations.",
            styles["Normal"],
        )
    )

    doc.build(elements)
    return pdf_path


# ═════════════════════════════════════════════════════════════════════
# TEST 1: PDF INGESTION
# ═════════════════════════════════════════════════════════════════════


class TestPDFIngestion:
    """Test the PDF ingestion layer."""

    def test_pdf_loads_all_pages(self, synthetic_pdf: Path):
        """The loader should extract all 3 pages from the synthetic PDF."""
        from ingestion.pdf_loader import load_pdf

        pages = load_pdf(str(synthetic_pdf))

        assert len(pages) == 3, f"Expected 3 pages, got {len(pages)}"

    def test_pdf_has_text(self, synthetic_pdf: Path):
        """Every page should contain non-empty text."""
        from ingestion.pdf_loader import load_pdf

        pages = load_pdf(str(synthetic_pdf))

        for page in pages:
            assert page["text"].strip(), f"Page {page['page']} has no text"

    def test_pdf_tables_extracted(self, synthetic_pdf: Path):
        """At least some pages should have extracted tables."""
        from ingestion.pdf_loader import load_pdf

        pages = load_pdf(str(synthetic_pdf))
        total_tables = sum(len(p.get("tables", [])) for p in pages)

        assert total_tables >= 1, (
            f"Expected at least 1 table across 3 pages, got {total_tables}"
        )

    def test_pdf_metadata(self, synthetic_pdf: Path):
        """Each page dict should carry source and title metadata."""
        from ingestion.pdf_loader import load_pdf

        pages = load_pdf(str(synthetic_pdf))

        for page in pages:
            assert "source" in page, "Missing 'source' key"
            assert "page" in page, "Missing 'page' key"
            assert "title" in page, "Missing 'title' key"
            assert page["source"].endswith(".pdf")

    def test_pdf_file_not_found(self):
        """Should raise FileNotFoundError for a missing file."""
        from ingestion.pdf_loader import load_pdf

        with pytest.raises(FileNotFoundError):
            load_pdf("nonexistent_report.pdf")


# ═════════════════════════════════════════════════════════════════════
# TEST 2: RAG PIPELINE
# ═════════════════════════════════════════════════════════════════════


class TestRAGPipeline:
    """Test the chunking → embedding → retrieval pipeline."""

    def test_chunker_produces_documents(self, synthetic_pdf: Path):
        """Chunking the ingested pages should produce LangChain Documents."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        assert len(chunks) > 0, "Chunker produced no chunks"

        # Each chunk should be a LangChain Document.
        from langchain.schema import Document

        for c in chunks:
            assert isinstance(c, Document)
            assert c.page_content.strip()
            assert "chunk_index" in c.metadata
            assert "char_count" in c.metadata

    def test_faiss_store_persisted(self, synthetic_pdf: Path, tmp_vector_store):
        """Embedding should create a FAISS index on disk."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        store = embedder.embed_and_store(chunks, tmp_vector_store)

        assert store is not None
        assert store.index.ntotal > 0, "FAISS index has no vectors"

        # Files should exist on disk.
        store_dir = Path(tmp_vector_store)
        assert (store_dir / "index.faiss").exists()
        assert (store_dir / "index.pkl").exists()

    def test_retrieval_returns_results(self, synthetic_pdf: Path, tmp_vector_store):
        """Retrieving for a financial query should return relevant chunks."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder
        from rag.retriever import FinancialRetriever

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        store = embedder.embed_and_store(chunks, tmp_vector_store)

        retriever = FinancialRetriever(store)
        results = retriever.retrieve("debt equity ratio", k=3)

        assert len(results) > 0, "Retriever returned no results"
        assert len(results) <= 3

    def test_scored_retrieval(self, synthetic_pdf: Path, tmp_vector_store):
        """Scored retrieval should return tuples of (Document, float)."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder
        from rag.retriever import FinancialRetriever

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        store = embedder.embed_and_store(chunks, tmp_vector_store)

        retriever = FinancialRetriever(store)
        results = retriever.retrieve_with_scores("cash flow", k=3)

        assert len(results) > 0
        for doc, score in results:
            assert isinstance(score, float)
            assert score >= 0.0

    def test_hybrid_retrieval(self, synthetic_pdf: Path, tmp_vector_store):
        """Hybrid retrieval should boost results containing keywords."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder
        from rag.retriever import FinancialRetriever

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        store = embedder.embed_and_store(chunks, tmp_vector_store)

        retriever = FinancialRetriever(store)
        results = retriever.hybrid_retrieve(
            query="financial risk assessment",
            keywords=["debt", "equity", "liabilities"],
            k=3,
        )

        assert len(results) > 0


# ═════════════════════════════════════════════════════════════════════
# TEST 3: FINANCIAL RATIOS
# ═════════════════════════════════════════════════════════════════════


class TestFinancialRatios:
    """Unit tests for all 5 ratio methods + interpret_ratio."""

    def setup_method(self):
        from utils.financial_ratios import FinancialRatioEngine

        self.engine = FinancialRatioEngine()

    # ── debt_to_equity ──────────────────────────────────────────────

    def test_debt_to_equity_normal(self):
        result = self.engine.debt_to_equity(1_400, 500)
        assert result == 2.8

    def test_debt_to_equity_zero_equity(self):
        result = self.engine.debt_to_equity(1_000, 0)
        assert result is None

    def test_debt_to_equity_negative_debt(self):
        result = self.engine.debt_to_equity(-200, 500)
        assert result == -0.4

    def test_debt_to_equity_zero_debt(self):
        result = self.engine.debt_to_equity(0, 500)
        assert result == 0.0

    # ── current_ratio ───────────────────────────────────────────────

    def test_current_ratio_normal(self):
        result = self.engine.current_ratio(450, 500)
        assert result == 0.9

    def test_current_ratio_zero_liabilities(self):
        result = self.engine.current_ratio(450, 0)
        assert result is None

    def test_current_ratio_healthy(self):
        result = self.engine.current_ratio(3_000, 1_000)
        assert result == 3.0

    # ── profit_margin ───────────────────────────────────────────────

    def test_profit_margin_normal(self):
        result = self.engine.profit_margin(120, 800)
        assert result == 0.15

    def test_profit_margin_zero_revenue(self):
        result = self.engine.profit_margin(120, 0)
        assert result is None

    def test_profit_margin_loss(self):
        result = self.engine.profit_margin(-50, 800)
        assert result == -0.0625

    # ── debt_to_income ──────────────────────────────────────────────

    def test_debt_to_income_normal(self):
        result = self.engine.debt_to_income(360, 1_000)
        assert result == 0.36

    def test_debt_to_income_zero_income(self):
        result = self.engine.debt_to_income(500, 0)
        assert result is None

    def test_debt_to_income_high_risk(self):
        result = self.engine.debt_to_income(500, 1_000)
        assert result == 0.5  # > 0.43 threshold

    # ── quick_ratio ─────────────────────────────────────────────────

    def test_quick_ratio_normal(self):
        # (120 + 80 + 150) / 500 = 350 / 500 = 0.7
        result = self.engine.quick_ratio(120, 80, 150, 500)
        assert result == 0.7

    def test_quick_ratio_zero_liabilities(self):
        result = self.engine.quick_ratio(100, 50, 50, 0)
        assert result is None

    def test_quick_ratio_all_zero_numerator(self):
        result = self.engine.quick_ratio(0, 0, 0, 500)
        assert result == 0.0

    # ── interpret_ratio ─────────────────────────────────────────────

    def test_interpret_debt_to_equity_critical(self):
        result = self.engine.interpret_ratio("debt_to_equity", 2.8)
        assert result["status"] == "critical"
        assert result["value"] == 2.8

    def test_interpret_current_ratio_critical(self):
        result = self.engine.interpret_ratio("current_ratio", 0.9)
        assert result["status"] == "critical"

    def test_interpret_current_ratio_safe(self):
        result = self.engine.interpret_ratio("current_ratio", 2.0)
        assert result["status"] == "safe"

    def test_interpret_profit_margin_warning(self):
        result = self.engine.interpret_ratio("profit_margin", 0.07)
        assert result["status"] == "warning"

    def test_interpret_quick_ratio_warning(self):
        result = self.engine.interpret_ratio("quick_ratio", 0.8)
        assert result["status"] == "warning"

    def test_interpret_none_value(self):
        result = self.engine.interpret_ratio("debt_to_equity", None)
        assert result["status"] == "error"

    def test_interpret_unknown_ratio(self):
        with pytest.raises(ValueError, match="Unknown ratio"):
            self.engine.interpret_ratio("nonexistent_ratio", 1.0)

    def test_interpret_all_thresholds_have_keys(self):
        """Every interpretation should have value, status, and threshold."""
        test_cases = [
            ("debt_to_equity", 1.5),
            ("current_ratio", 1.2),
            ("profit_margin", 0.12),
            ("debt_to_income", 0.30),
            ("quick_ratio", 1.1),
        ]
        for name, val in test_cases:
            result = self.engine.interpret_ratio(name, val)
            assert "value" in result
            assert "status" in result
            assert "threshold" in result
            assert result["status"] in ("safe", "warning", "critical")


# ═════════════════════════════════════════════════════════════════════
# TEST 4: FULL PIPELINE (END-TO-END)
# ═════════════════════════════════════════════════════════════════════


class TestFullPipeline:
    """End-to-end integration test using the synthetic PDF and mocked LLM."""

    def test_full_analysis(self, synthetic_pdf: Path, tmp_vector_store):
        """run_analysis should produce a complete report with all expected fields."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder
        from graph.workflow import run_analysis

        # ── Ingest & embed ──────────────────────────────────────────
        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        embedder.embed_and_store(chunks, tmp_vector_store)

        # ── Override VECTOR_DB_PATH for the workflow ────────────────
        os.environ["VECTOR_DB_PATH"] = tmp_vector_store

        # ── Run the full pipeline ───────────────────────────────────
        from langchain.schema import Document as LCDoc

        docs = [
            LCDoc(page_content=p["text"], metadata={"source": p["source"]})
            for p in pages
        ]

        report = run_analysis(
            query="Analyze credit risk for ACME Corporation based on their 2024 annual report",
            documents=docs,
        )

        # ── Assertions ──────────────────────────────────────────────
        assert report is not None, "run_analysis returned None"
        assert isinstance(report, dict), "report should be a dict"

        # Risk level
        assert "risk_level" in report
        assert report["risk_level"] in ("LOW", "MEDIUM", "HIGH", "CRITICAL"), (
            f"Unexpected risk_level: {report['risk_level']}"
        )

        # Key metrics
        assert "key_metrics" in report
        assert isinstance(report["key_metrics"], list)

        # Sources
        assert "sources" in report
        assert isinstance(report["sources"], list)

        # Agent trace — all 6 agents should have executed
        assert "agent_trace" in report
        trace = report["agent_trace"]
        expected_agents = {"planner", "retriever", "analyst", "evaluator", "verifier", "reporter"}
        actual_agents = set(trace)
        assert expected_agents.issubset(actual_agents), (
            f"Missing agents in trace: {expected_agents - actual_agents}. "
            f"Trace: {trace}"
        )

        # Report structure completeness
        assert "summary" in report
        assert "risk_badge" in report
        assert "justification" in report
        assert "recommendations" in report
        assert "verification_status" in report
        assert "verification_notes" in report
        assert "anomalies" in report

    def test_report_has_badge(self, synthetic_pdf: Path, tmp_vector_store):
        """The risk badge should contain an emoji and the level."""
        from ingestion.pdf_loader import load_pdf
        from rag.chunker import DocumentChunker
        from rag.embedder import DocumentEmbedder
        from graph.workflow import run_analysis

        pages = load_pdf(str(synthetic_pdf))
        chunker = DocumentChunker()
        chunks = chunker.chunk_documents(pages)

        embedder = DocumentEmbedder()
        embedder.embed_and_store(chunks, tmp_vector_store)
        os.environ["VECTOR_DB_PATH"] = tmp_vector_store

        report = run_analysis(query="Assess ACME Corp credit risk")

        badge = report.get("risk_badge", "")
        level = report.get("risk_level", "")
        assert level in badge, (
            f"Badge '{badge}' should contain level '{level}'"
        )
